### ISSUE TITLE
 File /etc/php/7.0/fpm/pool.d/kanboard.conf is not removed when uninstalling kanboard

### ISSUE THREAD

**Issue by franc00018** [YunoHost-Apps/kanboard_ynh#109]
--- 

### Describe the bug

File /etc/php/7.0/fpm/pool.d/kanboard.conf is not removed when uninstalling kanboard

### Context

- Hardware: VPS bought online
- YunoHost version: 3.8.5.9
- I have access to my server: Through SSH
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- While uninstalling, php7.0-fpm didn't restart

### Steps to reproduce

```sh
    sudo yunohost app uninstall kanboard
    sudo yunohost service restart php7.0-fpm
```

### Quick fix

Removing the file manually allowed php7.0-fpm to restart
```
sudo rm /etc/php/7.0/fpm/pool.d/kanboard.conf
sudo yunohost service restart php7.0-fpm
```

### Expected behavior

php7.0-fpm should restart after uninstalling kanboard

### Logs

PHP7.0-FPM restart
https://paste.yunohost.org/raw/akowegaxoj

Kanboard uninstall
https://paste.yunohost.org/raw/aqazuhefok

**Comment by yalh76** [comment]
should be ok by now,
