### ISSUE TITLE
Mobile app and email

### ISSUE THREAD

**Issue by tutle** [YunoHost-Apps/kanboard_ynh#110]
I use to connect to kanboard via the [**mobile app**](https://play.google.com/store/apps/details?id=io.HarryCLucas.KanboardMobile&hl=en_US&gl=US) on a self hosted kanboard installation
With the yunohost install of kanboard, I have an error message with user and passw

I would like to change the domaine name of emails (kanboard is installed in a sub domaine of my main domain), is it possible ?
Sincerely

**Comment by tutle** [comment]
How to connect to kanboard without going trough sso panel ?

**Comment by yalh76** [comment]
> How to connect to kanboard without going trough sso panel ?

Only option is to make the application public
