### ISSUE TITLE
Upgrade failure

### ISSUE THREAD

**Issue by tutle** [YunoHost-Apps/kanboard_ynh#121]
Hello , when trying upgrade kanboard from 1.2.18~ynh2 to 1.2.20~ynh2
I have this message

Corrupt source
[Error] Upgrade failed.

**Comment by alexAubin** [comment]
Please share the **\*full\*** log ...

**Comment by bachy** [comment]
same here 
i lost kanbaord and can't restore from premigrate-backup
```
$ yunohost app upgrade kanboard
Info: Now upgrading kanboard...
Info: [....................] > Loading installation settings...
Info: [+...................] > Ensuring downward compatibility...
Info: [#+++................] > Backing up Kanboard before upgrading (may take a while)...
Info: [####+...............] > Making sure dedicated system user exists...
Info: [#####+..............] > Upgrading source files...
Warning: Corrupt source
Warning: [Error] Upgrade failed.
```
https://paste.yunohost.org/raw/akuvesabur
```
$ yunohost backup restore kanboard-pre-upgrade1
Error: This backup archive can not be restored because it comes from a too-old YunoHost version.
```
neither can i install it again :( (then restore the old db)
```
Info: Installing kanboard...
Info: [....................] > Validating installation parameters...
Info: [....................] > Storing installation settings...
Info: [+...................] > Creating a MySQL database...
Info: [#+..................] > Configuring system user...
Info: [##+.................] > Setting up source files...
Warning: Corrupt source
Error: Unable to install kanboard: An error occurred inside the app installation script
```
https://paste.yunohost.org/raw/okeligunep

**Comment by bachy** [comment]
ok finally restored my old kanboard by fixing the ynuohost-version in kanboard-pre-upgrade1.info.json wich was ```"from_yunohost_version": "BASH_XTRACEFD:"```

**Comment by tutle** [comment]
Hello, I still can't upgrade kanboard...
https://paste.yunohost.org/raw/ocifotayih

**Comment by tutle** [comment]
Hello, did anybody encountered and solved this upgrade failure ?

**Comment by ericgaspar** [comment]
@tutle Do you have plugins installed? It could be the source of the upgrade failure.

**Comment by tutle** [comment]
> 
> 
> @tutle Do you have plugins installed? It could be the source of the upgrade failure.

BINGO ! Thanks a lot, that was the problem !
