### ISSUE TITLE
Unable to load task [CSP problem]

### ISSUE THREAD

**Issue by mrtpcet** [YunoHost-Apps/kanboard_ynh#122]
Yunohost v4.2.6 (stable)
Kanboard v1.2.20~ynh3

### Problem : since the last update, i can't load my tasks. An infinite wheel turns inside them. 
The Firefox or Brave console seems to show me a CSP problem (cf. pictures).
I activate _CORS Everywhere_ extension but it don't work either.

![image](https://user-images.githubusercontent.com/60814449/122010919-e0db9f00-cdbb-11eb-8b2e-e9f909793c88.png)
![image](https://user-images.githubusercontent.com/60814449/122011002-f4870580-cdbb-11eb-8257-9c024fb40a42.png)

**Comment by ericgaspar** [comment]
could you try to install/upgrade from this branch? https://github.com/YunoHost-Apps/kanboard_ynh/tree/CSP
```
sudo yunohost app install https://github.com/YunoHost-Apps/kanboard_ynh/tree/CSP --debug
or
sudo yunohost app upgrade kanboard -u https://github.com/YunoHost-Apps/kanboard_ynh/tree/CSP --force
```

**Comment by mrtpcet** [comment]
> could you try to install/upgrade from this branch? https://github.com/YunoHost-Apps/kanboard_ynh/tree/CSP
> 
> ```
> sudo yunohost app install https://github.com/YunoHost-Apps/kanboard_ynh/tree/CSP --debug
> or
> sudo yunohost app upgrade kanboard -u https://github.com/YunoHost-Apps/kanboard_ynh/tree/CSP --force
> ```

Yes, it's working now !

**Comment by mrtpcet** [comment]
I have the same problem since the last update 1.2.21~ynh1

**Comment by ericgaspar** [comment]
can you upgrade from testing please?
`sudo yunohost app upgrade kanboard -u https://github.com/YunoHost-Apps/kanboard_ynh/tree/testing --force`

**Comment by mrtpcet** [comment]
Same problem after upgrade from testing

**Comment by MarinLGU** [comment]
Hello, I have the same problem here, could you manage to fix it ?
Thanks !

**Comment by ericgaspar** [comment]
I applyed the fix #127 by @Trickscenique. Can you upgrade from testing please?
`sudo yunohost app upgrade kanboard -u https://github.com/YunoHost-Apps/kanboard_ynh/tree/NGINX --force`

**Comment by MarinLGU** [comment]
It worked, thank you ! But how will I be notified of the next upgrade now that I'm on the NGINW branch ?

**Comment by ericgaspar** [comment]
There is nothing to do. When the version changes, the update is triggered automatically.

**Comment by jacen05** [comment]
Same problem here, and upgrading from testing branch did the trick. Thanks for the fix!
