### ISSUE TITLE
refused to apply inline style because it violates the following Content Security Policy directive

### ISSUE THREAD

**Issue by Trickscenique** [YunoHost-Apps/kanboard_ynh#127]
In order to apply inline style modify this file /etc/nginx/conf.d/your.kanboard.domain/kanboard.conf                                                                                     

Change this line 
` more_set_headers "Content-Security-Policy: default-src 'self' 'unsafe-eval' data:";`
to 

` more_set_headers "Content-Security-Policy: default-src 'self' 'unsafe-eval' data:; style-src 'self' 'unsafe-inline'";`

**Comment by ericgaspar** [comment]
Thanks for the fix! I hope this solves the issue.

**Comment by Trickscenique** [comment]
Perfect !
