### ISSUE TITLE
Authorize ics public link

### ISSUE THREAD

**Issue by Trickscenique** [YunoHost-Apps/kanboard_ynh#129]
By default ICS public links need SSO authentification, and in my case it's not working with SOGO. 
(ex: _https://your.domain?controller=ICalendarController&action=project&token=78f29a185e96c4d5f05ecbb743119a14fd48a2e331d26493cc7122952e2e_)
My temporary solution is to add **Kanboard** to **Visitors** group in Yunohost interface

Maybe a better solution could be to add in installation script a custom permission like this :
`ynh_permission_create --permission "ics" --url "/controller=ICalendarController" --allowed "visitors" --label "ICS Public access"`

To be tested!

**Comment by ericgaspar** [comment]
@Trickscenique Did you have time to test https://github.com/YunoHost-Apps/kanboard_ynh/pull/130 ?

**Comment by Trickscenique** [comment]
Sorry, it's a very busy period.

I'll try to test your commit during the summer.

	
*Nassim Ourami*
Directeur technique
***@***.*** ***@***.***>
06.78.44.11.87 <tel:06.78.44.11.87>
Fediverse : ***@***.***
Linkedin 
<https://www.linkedin.com/in/nassim-ourami>https://nassim.netlib.re 
<https://nassim.netlib.re>

Le 06/06/2022 à 15:00, Éric Gaspar a écrit :

**Comment by yalh76** [comment]
#130 merged in master
