### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by rmueck** [YunoHost-Apps/kanboard_ynh#178]
### Describe the bug

*Update failed*

### Context

- Hardware: *VPS*
- YunoHost version: 11.2.8.2 
- Kanboard (kanboard) from 1.2.33~ynh3 to 1.2.34~ynh1
- I have access to my server: *Through SSH*

### Steps to reproduce

Start update

### Expected behavior

Upgrade successful

### Logs

[Logs](https://paste.yunohost.org/raw/eroyomutan)

**Comment by ericgaspar** [comment]
#179 should fix the issue

**Comment by rmueck** [comment]
yeahhh ... fix is OK!  Thank you

**Comment by rmueck** [comment]
yeahhh ... fix is OK! Thank you
