### ISSUE TITLE
Update from version 1.2.33-ynh1 to 1.2.35-ynh3 failed

### ISSUE THREAD

**Issue by RubusFruticosus74** [YunoHost-Apps/kanboard_ynh#186]
Hi there!

### Describe the bug
An update from version 1.2.33-ynh1 to 1.2.35-ynh3 failed with message " Variable $admin wasn't initialized when trying to replace \_\_ADMIN__ in /var/www/kanboard/config.php"

### Logs

See the full update log here: https://paste.yunohost.org/raw/oqejifonil

**Comment by madmaxlamenace** [comment]
Same bug from 1.2.34-ynh2 to 1.2.35-ynh3

**Comment by ericgaspar** [comment]
is the new version 1.2.37~ynh1 solving the issue?

**Comment by madmaxlamenace** [comment]
Upgrade with 1.2.37 solved my issue. Thanks @ericgaspar
