### ISSUE TITLE
Failed to update

### ISSUE THREAD

**Issue by unsiteavous** [YunoHost-Apps/kanboard_ynh#196]
**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change_url...), you are on the right place!*
   - *Otherwise, the issue may be due to the app itself. Refer to its documentation or repository for help.*
   - *When in doubt, post here and we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

### Describe the bug

I'm not able to udpate kanboard since few days :

### Context

- Hardware: Old laptop or computer
- YunoHost version: 11.2.24 (stable)
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*

- Using, or trying to install package version/branch: 1.2.38~ynh1 
- If upgrading, current package version: 1.2.34~ynh2

### Steps to reproduce

Try to update kanboard, with command or web panel.

### Logs

```
Failed to update sources : YunoHost was able to download the asset 'main' (https://github.com/kanboard/kanboard/archive/refs/tags/v1.2.38.tar.gz) for kanboard, but the asset doesn't match the expected checksum. This could mean that some temporary network failure happened on your server, OR the asset was somehow changed by the upstream maintainer (or a malicious actor?) and YunoHost packagers need to investigate and perhaps update the app manifest to take this change into account.
    Expected sha256 checksum: a28a48326baf23d5473e946544cb239754d8452d8e68d4fb8431a913cc60dbe0
    Downloaded sha256 checksum: 8cb90a199c649ecaa1bb0f6a3d69550adae8ac52c9c6be825b56ab5731baed26
```

**Comment by ericgaspar** [comment]
should be fixed on testing with #197
