### ISSUE TITLE
Failed to upgrade

### ISSUE THREAD

**Issue by jcn50** [YunoHost-Apps/kanboard_ynh#208]
### Logs

Failed to update sources : YunoHost was able to download the asset 'main' (https://github.com/kanboard/kanboard/archive/refs/tags/v1.2.42.tar.gz) for kanboard, but the asset doesn't match the expected checksum. This could mean that some temporary network failure happened on your server, OR the asset was somehow changed by the upstream maintainer (or a malicious actor?) and YunoHost packagers need to investigate and perhaps update the app manifest to take this change into account.
Expected sha256 checksum: a5b9763825f8e0d123470ff18b558d4637d2b2c732353f1edca4d4f9462b59a8
Downloaded sha256 checksum: cf93c4ef4d3ef8f00e223eabdfc611399299aa1d7694429ccd678743bdef6772
Downloaded file size: 3.3M
Reverting sources...
Provisioning, deprovisioning, or updating resources for kanboard failed: YunoHost was able to download the asset 'main' (https://github.com/kanboard/kanboard/archive/refs/tags/v1.2.42.tar.gz) for kanboard, but the asset doesn't match the expected checksum. This could mean that some temporary network failure happened on your server, OR the asset was somehow changed by the upstream maintainer (or a malicious actor?) and YunoHost packagers need to investigate and perhaps update the app manifest to take this change into account.
Expected sha256 checksum: a5b9763825f8e0d123470ff18b558d4637d2b2c732353f1edca4d4f9462b59a8
Downloaded sha256 checksum: cf93c4ef4d3ef8f00e223eabdfc611399299aa1d7694429ccd678743bdef6772
Downloaded file size: 3.3M
Could not complete the operation 'Upgrade the 'kanboard' app'.

**Comment by looowizz** [comment]
I'm getting the same error when trying to install the app :/
