### ISSUE TITLE
User server timezone and language

### ISSUE THREAD

**Issue by Jibec** [YunoHost-Apps/kanboard_ynh#36]
Kanboard and yunohost are great tools together ! but it would be even better to include local server information when installing kanboard !
can you please take server default timezone and language  for kanboard ?
If not too difficult, setting the correct "Date format" and "date and time format" would be great.

here is what I have in bash
admin@ynh:~$ date ==> mercredi 20 juillet 2016, 23:59:47 (UTC+0200)
admin@ynh:~$ echo $LANG ==> fr_FR.UTF-

here is what I get in Kanboard :
for date : UTC
for language : english

thanks for your help

**Comment by lapineige** [comment]
Indeed it's a small, not important thing, but it would add more comfort after the installation.

**Comment by mbugeia** [comment]
I agree, I have to look at this to see if it's possible.

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/486

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
