### ISSUE TITLE
Doesn't allow me to add new users over its interface

### ISSUE THREAD

**Issue by nicopace** [YunoHost-Apps/kanboard_ynh#39]
Only works with Yunohost users, it says "Access Forbidden" when I try to login with a user/pass created inside Kanboard (a local user as Kanboard calls it).

**Comment by nicopace** [comment]
Also commented this on the yunohost forum: https://forum.yunohost.org/t/kanboard-package/78/22?u=nicopace

**Comment by mbugeia** [comment]
I understand your need but unfortunately, it's not a bug it's a feature :/
This package is configured to work with YunoHost SSO and this disables the local Kanboard user.
AFAIK doesn't allow you to set up multiple authentification sources.

If you really want to do this, you have to change the config file in /var/www/kanboard/config.php to disable SSO authentification but by doing this YunoHost user won't work anymore.
Note that the conf file will be overwritten with each package update, so if you modify it you will need to backup it and restore it each time you upgrade Kanboard package.

**Comment by nicopace** [comment]
So, it is not possible to have them both enabled? that would be an awesome default config

**Comment by mbugeia** [comment]
It's not a limit of the package, it's a limit of Kanboard.

**Comment by nicopace** [comment]
Well... that was the question :)
Thanks! will ask them to do it then, so we can all have that feature!

**Comment by maniackcrudelis** [comment]
To allow to connect with YunoHost users AND local users, you have to disable `REVERSE_PROXY_AUTH` in the config file `/var/www/kanboard/config.php`

So, by the way, you lose the advantage of the YunoHost SSO.

**Comment by nicopace** [comment]
Why would you loose the SSO?

**Comment by maniackcrudelis** [comment]
Because by disable `REVERSE_PROXY_AUTH`, you'll disable the capacity of Kanboard to handle the variable $remote_user.
So, even if the SSO send the variable to Kanboard, it doesn't handle it.

**Comment by nicopace** [comment]
Thanks for the clarification... despite that... it would be great to have all the awesome features of yunohost (centralized users + SSO) but not loose the ability of being able to create users just for that app.
Either way, don't worry... if I don't do it, and it is important just for me, then you can ignore it :)

**Comment by lapineige** [comment]
Thanks for the tip, it works on the current version.
(but this is not cool :/ - I hop they will change this behaviour in the future)
