### ISSUE TITLE
Upgrade to 1.0.42

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/kanboard_ynh#45]
1.0.42 version is   [out](https://kanboard.net/news/version-1.0.42).

**Comment by yannicka** [comment]
Or maybe to the latest version: 1.0.47 (https://kanboard.net/news/version-1.0.47).

**Comment by Jibec** [comment]
this is going to be fixed by https://github.com/YunoHost-Apps/kanboard_ynh/pull/52

**Comment by JimboJoe** [comment]
#52 has been merged to master.
This issue is now officially fixed 🎉
