### ISSUE TITLE
Cannot install plugins as admin

### ISSUE THREAD

**Issue by win8linux** [YunoHost-Apps/kanboard_ynh#47]
It seems that I can't install plugins from the web UI even as administrator. I checked my config.php, referencing the instructions from [this](https://kanboard.net/documentation/plugin-directory) page. Everything related is in order, though.

Relevant details from config.php:
`// Plugins directory`
`define('PLUGINS_DIR', 'plugins');      `                                                                                               

`// Plugins directory URL`
`define('PLUGIN_API_URL', 'https://kanboard.net/plugins.json');`

`// Enable/Disable plugin installer`
`define('PLUGIN_INSTALLER', true);`

**Comment by Jibec** [comment]
does it works of you copy the plugin directly in kandboard's plugins folder?

**Comment by Jibec** [comment]
this works fine for me using the current stable Kanboard, please open again if you still have this issue! thanks for your understanding
