### ISSUE TITLE
Error until other apps are installed

### ISSUE THREAD

**Issue by p3k** [YunoHost-Apps/kanboard_ynh#48]
On a fresh install of YH on an Odroid C1 I got an error when running Kanboard – the browser window shows the warning:

```
Internal Error: PHP extension required: "gd"
```

I installed some other apps (Nextcloud and OpenSondage IIRC) and tried again to file this issue report when the error surprisingly was gone. Thus, I assume one of the other apps installed the missing PHP extension…?

**Comment by frju365** [comment]
yes, the package which must be installed to solve this issue is : 
`php5-gd`

Hope that it will help you,
frju365

**Comment by p3k** [comment]
Well, as I wrote in the description, the issue was resolved “accidentally” by installing another app.

But I think it would be nice to solve this issue in the Kanboard installation script, wouldn’t it?

**Comment by JimboJoe** [comment]
Fixed in in testing by https://github.com/YunoHost-Apps/kanboard_ynh/pull/52

**Comment by Jibec** [comment]
fixe with #54
