### ISSUE TITLE
Ajouter des utilisateur sans sso Apps

### ISSUE THREAD

**Issue by michelwend** [YunoHost-Apps/kanboard_ynh#50]
Bonjour,
Existe-t-il un moyen de déclarer des utilisateurs qui puissent se connecter dans Kanboard sans passer par le sso mais en allant directement sur la page d'accueil du site. Je précise qu'à l'installation j'ai déclaré le site public. En vous remerciant pour vos réponses

**Comment by Jibec** [comment]
I don't think so, I understand kanboard will always use LDAP.
Have you tried this playing with this? https://kanboard.net/documentation/user-management What does it says?

**Comment by anmol26s** [comment]
@michelwend 
I should have opened a separate issue for it, but it was somewhat related to the topic that time.
See if this is what you wanted(I don't speak French): https://github.com/YunoHost-Apps/kanboard_ynh/issues/7#issuecomment-139865911

**Comment by Jibec** [comment]
as pointed by anmol26s, this issue already is tracked.
TL;DR; on peut désactiver le SSO pour permettre à Kanboard de gérer ses propres utilisateurs, mais pas avoir les deux mécanismes d'authentification de façon concomitante.
