### ISSUE TITLE
unable to download application

### ISSUE THREAD

**Issue by numberdotone** [YunoHost-Apps/kanboard_ynh#53]
Kanboard can't be installed:

> Unable to download application archive
> + wget -q -O /tmp/tmp.W4v0DPXRNP/application.zip https://kanboard.net/kanboard-1.0.41.zip

should point to [https://github.com/kanboard/kanboard/releases](https://github.com/kanboard/kanboard/releases)

**Comment by Fipaddict** [comment]
Hello,

Same error with 
- yunohost: 2.7.2
- yunohost-admin: 2.7.2
- moulinette: 2.7.2
- ssowat: 2.7.2

> 32672 INFO + wget -q -O /tmp/tmp.bAgpYRjnLU/application.zip https://kanboard.net/kanboard-1.0.41.zip
> 33652 INFO + ynh_doie 'Unable to download application archive'
> 33653 WARNING Unable to download application archive

**Comment by JimboJoe** [comment]
Fixed in in testing by https://github.com/YunoHost-Apps/kanboard_ynh/pull/52

**Comment by JimboJoe** [comment]
Testing has been merged to master.
This issue is now officially fixed 🎉
