### ISSUE TITLE
How to connect with Kandroid ?

### ISSUE THREAD

**Issue by Zykino** [YunoHost-Apps/kanboard_ynh#59]
Installed kanboard_ynh (not in public), using the login with SSO.
Wanted to connect to it with a "Kanboard Android app" (Kandroid for now).

It does not connect telling me to check the URL.
I think it's because it reach the yunohost login page instead of the kanboard login page.

Should I set the Kanboard app to be public?
Can I do this on the current install? Or do I have to backup, delete, install in public ? (Never did this yet so if you have the commands it will be helpfull.)

**Comment by Jibec** [comment]
Thanks for this issue, but this is an upstream bug in kandroid :( I won't be able to fix it here, the version number detection of kandroid is broken, please ask them to fix it faster ;) (with care)
-- 
Jean-Baptiste Holcroft

**Comment by Zykino** [comment]
Yes I saw https://github.com/andresth/Kandroid/issues/38.

But isn't it because if I visit my Kanboard page from a private browsing session I'm redirected to the sso login page instead of the Kanboard login page?
I don't think it's Kandroid's job to know how to connect to yunohost (or any other sso).

My error is:
"Invalid response from server.
Please check URL."
and not "This server uses a version below 1.0.38. Please Upgrade".

Maybe it's not a code issue but a "Please add a doc about passing an app from private to public". Maybe it exist for yunohost global and I didn't found it. (A link in the wiki/README would be helpfull for that.)

**Comment by lapineige** [comment]
> Maybe it's not a code issue but a "Please add a doc about passing an app from private to public". Maybe it exist for yunohost global and I didn't found it. (A link in the wiki/README would be helpfull for that.)

There are several topics in Yunohost.org forum explaining how to do it (I don't have a link here).
But yeah it's definitely something to add to the wiki.

**Comment by Jibec** [comment]
@Zykino you're totally right!
This Pull Request already fixes this https://github.com/YunoHost-Apps/kanboard_ynh/pull/55

@lapineige well, here there is a proper fix, no need to make this app public for this.

I'm closing this, please reopen if Kandroid fixes his bug.
