### ISSUE TITLE
 Error message "Access Forbidden"

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/kanboard_ynh#68]
Hi
I am unable to login to Kanboard on a fresh install with LDAP. After I try to login with my SSO username and password there is an error message "Access Forbidden". I tried to reset the password but the link to new password does not work.
I am on Debian stretch.

**Comment by anmol26s** [comment]
Its defined as true.

```
// Enable/disable the reverse proxy authentication
define('REVERSE_PROXY_AUTH', true);
```

**Comment by anmol26s** [comment]
Somebody have similar problem or looked into this issue?

**Comment by Jibec** [comment]
well, please enable debug: https://github.com/YunoHost-Apps/kanboard_ynh/blob/master/conf/config.php#L7

And search logs for a relevant error message please.

**Comment by anmol26s** [comment]
There is no error message in debug. Can this be related to stretch ? Has someone tested Kanboard on YunoHost 3 ?

**Comment by anmol26s** [comment]
I have solved the issue by disabling reverse proxy authentication. 

```
// Enable/disable the reverse proxy authentication
define('REVERSE_PROXY_AUTH', false);
```
Someone is facing similar problem debian stretch ?

**Comment by lapineige** [comment]
> (true is needed to use SSO, false to use "classical" accounts (not SSO ones), as Kanboard doesn't support both activated at the same time, yet)

That a general issue, due to Kanboard way of handling accounts, as far as I know. Not related to Stretch.

**Comment by anmol26s** [comment]
But why is  **reverse proxy authentication** kept true in the package then ? It wasted my 2 hours finding the solution.

**Comment by lapineige** [comment]
Because by default it uses Yunohost SSO, I guess.
This tip tip as to be added in the readme, indeed.
