### ISSUE TITLE
No php-fpm.ini file?

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/kanboard_ynh#69]
Hi
The app don't have php-fpm.ini file for its configuration. Is that done for a reason?

**Comment by maniackcrudelis** [comment]
All the informations supposed to be in this file were put in the [.conf file](https://github.com/YunoHost-Apps/kanboard_ynh/blob/master/conf/php-fpm.conf#L67-L72). Which is works also, but to keep those additional information clearer, it's better to use a .ini file indeed.
That's and old part of code. Don't hesitate to propose a fix for that.
