### ISSUE TITLE
This PHP extension is required: "mbstring"

### ISSUE THREAD

**Issue by Bobcadence** [YunoHost-Apps/kanboard_ynh#74]
After a fresh install mondomaine.nohost.me/kanboard/ bring me a error 
Internal Error: This PHP extension is required: "mbstring"

I'am on lime 2 V3.0 imag + update:
- Debian 9.5 32bit (Linux 4.14.18-sunxi)
- yunohost: 3.0.0.1 (stable)
- yunohost-admin: 3.0.0 (stable)
- moulinette: 3.0.0 (stable)
- ssowat: 3.0.0 (stable)

**Comment by maniackcrudelis** [comment]
Already fix in the current [testing](https://github.com/YunoHost-Apps/kanboard_ynh/pull/72) by this commit https://github.com/YunoHost-Apps/kanboard_ynh/pull/72/commits/48bd657d121e57c1fc02fa451dd55be237c8712a
It's ongoing.
