### ISSUE TITLE
Using Kandroid 0.5.9.19 updating kanboard gives error "SetEnvIf Authorization .+ HTTP_AUTHORIZATION=$0"

### ISSUE THREAD

**Issue by TiberiusRegenschein** [YunoHost-Apps/kanboard_ynh#87]
Initial login is fine into kanboard via kandroid. Only if trying to update an entry or updating the kanboard the error message appears. This can be as bad as the whole yunohost instance being unresponsive for a while. A hint maybe given in the forum entry: https://forum.yunohost.org/t/kanboard-connecter-kandroid-a-kanboard/7695 
This was there with 1.2.9 but not before.
The KanDroid app is a very useful extension and does not seem to have the same issue with installations not on yunohost. LDAP problem?

Thanks for fixing

**Comment by yalh76** [comment]
You should make the applicaiton public
