### ISSUE TITLE
Kanboard's public access mode not working with private instance

### ISSUE THREAD

**Issue by MayeulC** [YunoHost-Apps/kanboard_ynh#89]
Kanboard has a public access mode for private projects. I would like to share these links, whithout requiring people to log in.

![image](https://user-images.githubusercontent.com/3952726/67697251-8acca480-f9a8-11e9-88e9-a5c12a645beb.png)

But Right now, I am getting the SSO login page.

The URLs are:
* https://subdomain.example.com/kanboard/?controller=BoardViewController&action=readonly&token=<the_token>
* https://subdomain.example.com/kanboard/?controller=FeedController&action=project&token=<the_token>
* https://subdomain.example.com/kanboard/?controller=ICalendarController&action=project&token=<the_token>

I do not necessarily want the kanboard instance to be public for this to work, so this probably needs some whitelisting in nginx, but I am unsure how to interact with the yunohost SSO to do it.

**Comment by yalh76** [comment]
To be able to share to public without login, you should make the application public
