### ISSUE TITLE
Gantt Plugin Not in Plugin Directory

### ISSUE THREAD

**Issue by jeremylow** [YunoHost-Apps/kanboard_ynh#92]
Hey y'all - 

Installed Kanboard and went to enable Gantt charts, but the plug in is not listed in the directory (I believe it is in a non-YUNH context) and I don't see the option of using Gantt charts. Something I'm missing or is there a bug in how this is deployed?

Thanks!

Info:
Application version: 1.2.12
PHP version: 7.0.33-0+deb9u6
PHP SAPI: fpm-fcgi
HTTP Client: cURL
OS version: Linux 4.9.0-9-amd64
Database driver: mysql
Database version: 10.1.41-MariaDB-0+deb9u1

**Comment by ericgaspar** [comment]
Fixed with #135
