### ISSUE TITLE
Add support for cron

### ISSUE THREAD

**Issue by mdeabreu** [YunoHost-Apps/kanboard_ynh#96]
Kanboard contains the ability to create automatic actions that can fire based on a number of conditions. One such condition is when a task due date is coming up. This requires a cron entry to fire which will run these background tasks. It seems that the current package does not install an entry into the crontab and as a result these background tasks never fire.

![image](https://user-images.githubusercontent.com/1589244/85051908-f6889b00-b14c-11ea-9da4-1d46626d834c.png)

Here is an image of one of the automatic actions.

**Expected result**
4 days before a tasks due date the task should move from the Backlog column to the Ready column.

**Actual result**
Any tasks that should meet the criteria do not move and remain in the Backlog column.

Here is the crontab that the upstream project normally needs: https://github.com/kanboard/kanboard/blob/master/docker/etc/crontabs/nginx
```
0 8 * * * cd /var/www/app && ./cli cronjob >/dev/null 2>&1
```

**Comment by ericgaspar** [comment]
Should be solved with #100
