### ISSUE TITLE
installing plugins

### ISSUE THREAD

**Issue by NathanRussellUK** [YunoHost-Apps/kanboard_ynh#97]
hiya

just had a bit of playing about to get plugins installing correctly!

it was by and large what the docs say (install php-zip, make sure the plugins dir is chmod 755) with the difference that the user group shouldn't be www-data but stay as kanboard.

i wonder two things really:
- could php-zip be installed alongside kanboard/ perhaps have it as a configurable extra via the yunohost gui installation?
- is it worth documenting the www-data/ kanboard distinction?

**Comment by ericgaspar** [comment]
`php-zip` installed as standard with #99
