### ISSUE TITLE
Kanboard can break Fail2ban after restoring a backup on a fresh installation

### ISSUE THREAD

**Issue by rasmus-mk** [YunoHost-Apps/kanboard_ynh#98]
Versions: 
Kanboard: 1.2.12~ynh1
Yunohost: 4.0.4

I had Kanboard break Fail2ban after restoring a backup on a fresh installation of Yunohost (restored backup instead of doing post-install).
Steps:
- Before doing the backup I had a something.nohost.me domain as my main domain.
- Installed Kanboard
- Changed default domain to my own domain and removed the something.nohost.me domain
- Created a backup
- Restored the backup on the fresh installation
At this point the Fail2ban service does not start.

The reason seems to be the config file /etc/fail2ban/jail.d/kanboard.conf that points to the Nginx log file of the old domain (in my case something.nohost.me). This config file wasn't updated with the new domain when the domain change is done. Fail2ban keeps working after the change because the log files for the old domain are not removed in the change either. However, they are not a part of the backup and so when it is restored Fail2ban refuses to start because it cannot read the log files.

Adjusting kanboard.conf solves this problem.

**Comment by rasmus-mk** [comment]
I think I see how this should be fixed in the change_url script. 
I guess I could create a PR for this. Would that be welcome?

**Comment by alexAubin** [comment]
>Would that be welcome?

Yes absolutely :stuck_out_tongue_winking_eye:
